### ISSUE TITLE
Exception while trying to authenticate with email + password

### ISSUE THREAD

**Issue by ikus060** [tmunzer/Mist_library#7]
When trying to provide credentials using username and password, the script fail with a stack trace.

```
ERROR    : Authentication failed: Incorrect authentication credentials.

Traceback (most recent call last):
  File "/home/ikus060/Downloads/mist_library/org_conf_backup.py", line 324, in <module>
    mist_session = mist_lib.Mist_Session(session_file)
  File "/home/ikus060/Downloads/mist_library/mlib/mist.py", line 96, in __init__
    self._login()
  File "/home/ikus060/Downloads/mist_library/mlib/mist.py", line 234, in _login
    self._set_login_password()
AttributeError: 'Mist_Session' object has no attribute '_set_login_password'
```

Indeed, `_set_login_password` is not a declared function ion the code.

**Comment by tmunzer** [comment]
Hi Patrik,

I'll check that this week.
